version: '3.8'

services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - POSTGRES_USER=local-user
      - POSTGRES_PASSWORD=local-password
      - POSTGRES_DB=calculator
    ports:
      - '5432:5432'
    volumes:
      -  ./dev/:/docker-entrypoint-initdb.d/
